### ISSUE TITLE
Add descriptions for the permissible values in the `DisplaySectionTypeEnum` enumeration

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/analysis-results-standard#210]
The permissible values in the `DisplaySectionTypeEnum` are missing descriptions, which should be added.

I started drafting descriptions by copying the definitions from "Table 1: Parts of a Table" in the PHUSE [General Output Tips and Considerations](https://phuse.s3.eu-central-1.amazonaws.com/Deliverables/Standard+Analyses+and+Code+Sharing/General+Output+Tips+and+Considerations.pdf) white paper:
```
  DisplaySectionTypeEnum:
    description: Types of display section that contain one or more pieces of informational text.
    permissible_values:
      Title:
        description: >
          The title is a caption of a table beginning with "Table" followed by sequenced numbers or letters and separated by full stops.
          The title includes additional lines describing the content.
      Rowlabel Header:
        description:
      Legend:
        description: >
          Lines of text placed immediately after the body of the table containing statements explaining the use of terms or values.
          May be prefaced with a word such as 'Note:'.
      Abbreviation:
        description: Lines of text defining abbreviations, acronyms, and terms used in the body of the display.
      Footnote:
        description:
```
However:
- There is no description for "Rowlabel Header", so we need to define one. (In fact, the white paper says "A stub does not require a column heading.")
- The definition for "Footnotes" does not align with how some footnotes and legends have been defined in the example reporting events:
  > Placed after the abbreviations and definitions, if any. Footnotes lead with symbols (asterisk, dagger, double dagger, or section symbol) or superscripted letters (<sup>a, b, c</sup>) or numbers (<sup>1, 2, 3</sup>) which are in the table behind units of measure or words. Footnotes add information regarding the associated values where they occur in the body.

  Which of the following two options should be applied?:
    1. Use the PHUSE definition(s) and update the examples, e.g.:
        - Change things like `Source dataset: adsl, Generated on: DDMONYYYY:HH:MM` from a footnote to a legend.
        - Change things like `[a] Dose Modification includes Dose Reduced; Drug Interrupted in the AE action taken with study treatment.` from a legend to a footnote.
    2. Use different definition(s).
